### ISSUE TITLE
Not all logs are rotated

### ISSUE THREAD

**Issue by pavl00** [geeooff/iis-log-rotator#2]
Sometimes IIS is creating daily logs with file name ending on -x.log: "u_ex{0:yyMMdd}-x.log" and that logs are not rotated.
Rotated are only logs in this format "u_ex{0:yyMMdd}.log"
![image](https://github.com/geeooff/iis-log-rotator/assets/15629355/d61bfae5-24e9-4fe1-b0b1-55411f836142)

**Comment by geeooff** [comment]
Hey @pavl00, thank you for submitting an issue.

This tool is not really under active development (I should have set it as an archived repo), so I can't promise I'll push a fix.

Can you please dump your site XML configuration, so I can try to reproduce it?
Thank you again.

**Comment by serdjeek** [comment]
Hi, @geeooff !
This problem manifests itself in the presence of custom fields in the log. In this case, IIS appends _x to the filename.
Can you fix this, or may it possible to take out the log filename template in the config?
Thank you again. Really great tool!

**Comment by geeooff** [comment]
@pavl00, @serdjeek Please test this preview release that should resolve your issue:
https://github.com/geeooff/iis-log-rotator/releases/tag/v1.10-preview

Thank you @serdjeek for pointing me in the right direction.
